services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    hostname: vaultwarden
    restart: always
    env_file:
      - /Volumes/docker/vaultwarden/.env
    volumes:
      - /Volumes/docker/vaultwarden/data:/data
      - /Volumes/docker/vaultwarden/logs:/logs
    ports:
      - "9443:443" # Le reverse proxy se connectera à ce port en interne
      - "3012:3012" # Port WebSocket
    networks:
      - infrastructure_network
    mem_limit: 12g
    mem_reservation: 2g
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
networks:
  infrastructure_network:
    external: true
